#!/bin/sh
echo "assigning variables"
HOST='Redacted'
USER="Redacted.${3}"
PASSWD='Redacted'
echo $1
echo $2
echo $3

echo "starting ftp"
ftp -p -n $HOST <<END_SCRIPT
quote USER $USER
quote PASS $PASSWD
binary
cd $2
mget $1
quit
END_SCRIPT
cd ..
echo "finished"
exit 0